# Generated by Django 4.0.3 on 2022-04-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='super_type',
            new_name='Super_type',
        ),
    ]
