# Generated by Django 4.0.3 on 2022-04-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='seconday_ability',
            new_name='secondary_ability',
        ),
    ]
