# Generated by Django 4.0.3 on 2022-04-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_seconday_ability_super_secondary_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
